MVC-Burger-Project/Areas/CustomerPanel/Controllers/PanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_Burger_Project.DAL;
using MVC_Burger_Project.Models.Entities;
using MVC_Burger_Project.Models.ViewModels;

namespace MVC_Burger_Project.Areas.CustomerPanel.Controllers
{
    [Authorize(Roles = "Customer")]
    [Area("CustomerPanel")]
    public class PanelController : Controller
    {
        private readonly Context _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly MenuViewModel menuModel;

        public PanelController(Context context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            menuModel = new MenuViewModel();
        }

        public IActionResult CustomerIndex()
        {
            return View();
        }

        public async Task<IActionResult> Edit(int id)
        {
            AppUser appUser = await _userManager.GetUserAsync(User);

            return View(appUser);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AppUser updatedUser)
        {
            AppUser appUser = await _userManager.GetUserAsync(User);
            appUser.FirstName = updatedUser.FirstName;
            appUser.LastName = updatedUser.LastName;
            appUser.Email = updatedUser.Email;
            appUser.UserName = updatedUser.Email;
            appUser.NormalizedEmail = updatedUser.Email.ToUpper();
            appUser.NormalizedUserName = updatedUser.Email.ToUpper();
            if (updatedUser.PasswordHash != null)
            {
                appUser.PasswordHash = _userManager.PasswordHasher.HashPassword(appUser, updatedUser.PasswordHash);
            }
            appUser.Address = updatedUser.Address;

            _context.SaveChanges();

            return Redirect("/CustomerPanel/Panel/CustomerIndex");
        }

        public async Task<IActionResult> GetOrders (int id)
        {
            AppUser appUser = await _userManager.GetUserAsync(User);

            menuModel.Orders = _context.Orders.Include(b => b.Burger).ThenInclude(bi => bi.BurgerIngredients).ThenInclude(i => i.Ingredient).Include(m => m.Drink).Include(m => m.Side).Include(m => m.Size).Include(s => s.Sauce).Where(x => x.AppUser.Id == appUser.Id).ToList();

            return View(menuModel);
        }
    }
}

MVC-Burger-Project/Areas/ManagerPanel/Controllers/PanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MVC_Burger_Project.Models.Entities;

namespace MVC_Burger_Project.Areas.ManagerPanel.Controllers
{
    [Area("ManagerPanel")]
    //[Authorize(Roles = "Manager")]

    //[Authorize(Policy = "RequireAdminRole")]
    public class PanelController : Controller
    {
        private readonly UserManager<AppUser> _userManager;

        public PanelController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult ManagerIndex()
        {
            return View();
        }
        public async Task<IActionResult> AdminUserOlustur()
        {
            AppUser user = new AppUser()
            {
                FirstName = "BarCode",
                LastName = "Yazılım",
                Address = "Istanbul",
                Email = "yazilim_barcode@gmail.com",
                UserName = "yazilimbarcode@gmail.com",
            };

            await _userManager.CreateAsync(user, "Brcd.123");
            await _userManager.AddToRoleAsync(user, "Manager");

            return Content("Barcode Admin Olustu");
        }
    }
}

MVC-Burger-Project/Areas/CustomerPanel/Views/Panel/CustomerIndex.cshtml
<h2 class="text-center" style="margin-top:200px">Customer Panel</h2>

<div class="row justify-content-around mt-5">
    <div class="card col-md-4" style="height:500px">
        <p class="card-img-top text-center" style="font-size:100px; margin-top:50px"><i class="fa-solid fa-user"></i></p>
        <div class="card-body text-center">
            <h5 class="card-title mt-5">Account Options</h5>
            <p class="card-text mt-3">To change your account information</p>
            <a asp-area="CustomerPanel" asp-controller="Panel" asp-action="Edit" class="btn btn-primary mt-5">Click Here</a>
        </div>
    </div>
    <div class="card col-md-4" style="height:500px">
        <p class="card-img-top text-center" style="font-size:100px; margin-top:50px"><i class="fa-solid fa-cart-shopping"></i></p>
        <div class="card-body text-center">
            <h5 class="card-title mt-5">Order Information</h5>
            <p class="card-text mt-3">To see your orders</p>
            <a asp-area="CustomerPanel" asp-controller="Panel" asp-action="GetOrders" class="btn btn-primary mt-5">Click Here</a>
        </div>
    </div>
</div>

MVC-Burger-Project/Areas/CustomerPanel/Views/Panel/Edit.cshtml
@model MVC_Burger_Project.Models.Entities.AppUser

@{
    ViewData["Title"] = "Edit";
}
<div class="row" style="margin-top:200px">
    <div class="container col-md-4">
        <h1 class="text-center">Edit</h1>
        <h4 class="text-center">Edit Account Information</h4>
        <hr />
        <form asp-action="Edit" style="margin-top:50px">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">First Name</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Last Name</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label">Address</label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">E-mail</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PasswordHash" class="control-label">Password</label>
                <input type="password" asp-for="PasswordHash" value="" class="form-control" />
                <span asp-validation-for="PasswordHash" class="text-danger"></span>
            </div>
            <div class="form-group mt-3 text-center" style="margin-bottom:220px">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="CustomerIndex" class="btn btn-outline-dark text-center" style="margin-left:20px">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MVC-Burger-Project/Areas/CustomerPanel/Views/Panel/GetOrders.cshtml
@using MVC_Burger_Project.Models.ViewModels;
@model MenuViewModel

@{
    ViewData["Title"] = "GetOrders";
}

<section class="h-100" style=" margin-top:200px">
    <div class="container h-100 py-5">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-8">

                <div class="d-flex justify-content-between align-items-center mb-4">
                    <h3 class="fw-normal mb-0 text-black">My Orders</h3>
                </div>
                @if (Model.Orders.Count < 1)
                {
                    <div class="card rounded-3 mb-4">
                        <div class="card-body p-4">
                            <div class="row d-flex justify-content-between align-items-center ">
                                <p>Sepette Ürün Bulunamamıştır</p>
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    @foreach (Order order in Model.Orders)
                    {
                        @if (order.Burger == null)
                        {
                            @if (order.Sauce == null)
                            {
                                @if (order.Drink == null)
                                {
                                    @if (order.Side == null && Model == null)
                                    {
                                        <div class="card rounded-3 mb-4">
                                            <div class="card-body p-4">
                                                <div class="row d-flex justify-content-between align-items-center " style="margin-top:200px">
                                                    <p>Sepette Ürün Bulunamamıştır</p>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="card rounded-3 mb-4">
                                            <div class="card-body p-4">
                                                <div class="row d-flex justify-content-between align-items-center">
                                                    <div class="col-md-2 col-lg-2 col-xl-2">
                                                        <img src="~/img/side/@order.Side.Picture"
                                                             class="img-fluid rounded-3" alt="@order.Side.Name">
                                                    </div>
                                                    <div class="col-md-3 col-lg-3 col-xl-3">
                                                        <p class="lead fw-normal mb-2">@order.Side.Name</p>

                                                    </div>
                                                    <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                                        <h5 class="mb-0">@order.TotalPrice</h5>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                }
                                else
                                {
                                    <div class="card rounded-3 mb-4">
                                        <div class="card-body p-4">
                                            <div class="row d-flex justify-content-between align-items-center">
                                                <div class="col-md-2 col-lg-2 col-xl-2">
                                                    <img src="~/img/drink/@order.Drink.Picture"
                                                         class="img-fluid rounded-3" alt="@order.Drink.Name">
                                                </div>
                                                <div class="col-md-3 col-lg-3 col-xl-3">
                                                    <p class="lead fw-normal mb-2">@order.Drink.Name</p>

                                                </div>
                                                <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                                    <h5 class="mb-0">@order.TotalPrice</h5>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            }
                            else
                            {
                                <div class="card rounded-3 mb-4">
                                    <div class="card-body p-4">
                                        <div class="row d-flex justify-content-between align-items-center">
                                            <div class="col-md-2 col-lg-2 col-xl-2">
                                                <img src="~/img/sauce/@order.Sauce.Picture"
                                                     class="img-fluid rounded-3" alt="@order.Sauce.Name">
                                            </div>
                                            <div class="col-md-3 col-lg-3 col-xl-3">
                                                <p class="lead fw-normal mb-2">@order.Sauce.Name</p>

                                            </div>
                                            <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                                <h5 class="mb-0">@order.TotalPrice</h5>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                        else
                        {
                            <div class="card rounded-3 mb-4">
                                <div class="card-body p-4">
                                    <div class="row d-flex justify-content-between align-items-center">
                                        <div class="col-md-2 col-lg-2 col-xl-2">
                                            <img src="~/img/burger/@order.Burger.Picture"
                                                 class="img-fluid rounded-3" alt="@order.Burger.Name">
                                        </div>
                                        <div class="col-md-3 col-lg-3 col-xl-3">
                                            <p class="lead fw-normal mb-2">@order.Burger.Name Menu</p>
                                            <p><span class="text-muted">Size: </span>@order.Size.Name <br /><span class="text-muted">Drink: </span>@order.Drink.Name <br /><span class="text-muted">Sauce: </span>@order.Sauce.Name <br /><span class="text-muted">Side: </span>@order.Side.Name </p>
                                        </div>
                                        <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                            <h5 class="mb-0">@order.TotalPrice</h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                }




                @*      <div class="card rounded-3 mb-4">
                <div class="card-body p-4">
                <div class="row d-flex justify-content-between align-items-center">
                <div class="col-md-2 col-lg-2 col-xl-2">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-shopping-carts/img1.webp"
                class="img-fluid rounded-3" alt="Cotton T-shirt">
                </div>
                <div class="col-md-3 col-lg-3 col-xl-3">
                <p class="lead fw-normal mb-2">Basic T-shirt</p>
                <p><span class="text-muted">Size: </span>M <span class="text-muted">Color: </span>Grey</p>
                </div>
                <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                <button class="btn btn-link px-2"
                onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                <i class="fas fa-minus"></i>
                </button>

                <input id="form1" min="0" name="quantity" value="2" type="number"
                class="form-control form-control-sm" />

                <button class="btn btn-link px-2"
                onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                <i class="fas fa-plus"></i>
                </button>
                </div>
                <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                <h5 class="mb-0">$499.00</h5>
                </div>
                <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                <a href="#!" class="text-danger"><i class="fas fa-trash fa-lg"></i></a>
                </div>
                </div>
                </div>
                </div>*@





            </div>
        </div>
    </div>
</section>